name: "🐛 Fix"
description: "버그 수정"
labels: ["fix"]
body:
  - type: textarea
    attributes:
      label: 📄 버그 설명
      description: 발생한 버그에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🔍 재현 방법
      description: 버그를 재현할 수 있는 단계를 작성해 주세요.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💡 예상 동작
      description: 정상적으로 동작했을 때 기대하는 결과를 작성해 주세요.
      placeholder: 어떻게 동작해야 하나요?
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
      placeholder: 최대한 세분화 해서 적어주세요!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
